.TH GIRACOIN-CLI "1" "February 2016" "giracoin-cli 0.12"
.SH NAME
giracoin-cli \- a remote procedure call client for Giracoin Core. 
.SH SYNOPSIS
giracoin-cli [options] <command> [params] \- Send command to Giracoin Core. 
.TP
giracoin-cli [options] help \- Asks Giracoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the giracoin-cli program. giracoin-cli is an RPC client used to send commands to Giracoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBgiracoind\fP, \fBgiracoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
